# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dvarapala < Formula
  desc "MCP security gateway — drop-in protection for MCP servers"
  homepage "https://github.com/TharVid/dvarapala"
  version "0.1.11"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tharvid/dvarapala/releases/download/v0.1.11/dvarapala_0.1.11_macos_x86_64.tar.gz"
      sha256 "3ab2e84c17d9e8f0c2918fce5239e35578ba14569a059d31f7bccd159c256e88"

      define_method(:install) do
        bin.install "dvarapala"
        pkgshare.install Dir["policies/*"] if Dir.exist?("policies")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tharvid/dvarapala/releases/download/v0.1.11/dvarapala_0.1.11_macos_arm64.tar.gz"
      sha256 "8acd981c56b4d20106e8207ef90c411a0b6a8db7d805cabc4548f719ccc1779c"

      define_method(:install) do
        bin.install "dvarapala"
        pkgshare.install Dir["policies/*"] if Dir.exist?("policies")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tharvid/dvarapala/releases/download/v0.1.11/dvarapala_0.1.11_linux_x86_64.tar.gz"
      sha256 "6eaa13087c59723d78f7c39fad9873957026f310e56275432929b9a4361a8a55"
      define_method(:install) do
        bin.install "dvarapala"
        pkgshare.install Dir["policies/*"] if Dir.exist?("policies")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tharvid/dvarapala/releases/download/v0.1.11/dvarapala_0.1.11_linux_arm64.tar.gz"
      sha256 "5857cce1efa0faa7bc9e9fd89c08530fe1f1bc0890c21de3070e83237102d3b8"
      define_method(:install) do
        bin.install "dvarapala"
        pkgshare.install Dir["policies/*"] if Dir.exist?("policies")
      end
    end
  end

  test do
    system "#{bin}/dvarapala", "version"
  end
end
