# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dvarapala < Formula
  desc "MCP security gateway — drop-in protection for MCP servers"
  homepage "https://github.com/TharVid/dvarapala"
  version "0.1.12"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tharvid/dvarapala/releases/download/v0.1.12/dvarapala_0.1.12_macos_x86_64.tar.gz"
      sha256 "0c794d55093312e07fe545d6a8adbd25fcdbfed04e941709acba6741a691c3bc"

      define_method(:install) do
        bin.install "dvarapala"
        pkgshare.install Dir["policies/*"] if Dir.exist?("policies")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tharvid/dvarapala/releases/download/v0.1.12/dvarapala_0.1.12_macos_arm64.tar.gz"
      sha256 "2495df76bbdca5bca9842e0624f0accdf8a43a5b4ab3213d746fc2ffed1153e5"

      define_method(:install) do
        bin.install "dvarapala"
        pkgshare.install Dir["policies/*"] if Dir.exist?("policies")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tharvid/dvarapala/releases/download/v0.1.12/dvarapala_0.1.12_linux_x86_64.tar.gz"
      sha256 "849b7d3ea3c4e0b13e39c58a8aca8255ba84f1b9b7757e44365cfa51f67fe1ca"
      define_method(:install) do
        bin.install "dvarapala"
        pkgshare.install Dir["policies/*"] if Dir.exist?("policies")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tharvid/dvarapala/releases/download/v0.1.12/dvarapala_0.1.12_linux_arm64.tar.gz"
      sha256 "8b2dddf2d9c9af92ce9bf562b6e9dec91e7533fc28be86a6bf57441b32e2a633"
      define_method(:install) do
        bin.install "dvarapala"
        pkgshare.install Dir["policies/*"] if Dir.exist?("policies")
      end
    end
  end

  test do
    system "#{bin}/dvarapala", "version"
  end
end
