# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dvarapala < Formula
  desc "MCP security gateway — drop-in protection for MCP servers"
  homepage "https://github.com/TharVid/dvarapala"
  version "0.1.9"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tharvid/dvarapala/releases/download/v0.1.9/dvarapala_0.1.9_macos_x86_64.tar.gz"
      sha256 "8e6ab4e73fe714d55fc6dc6d6d8ef727e7ea4b74245b9518c9642f1c28fd398d"

      define_method(:install) do
        bin.install "dvarapala"
        pkgshare.install Dir["policies/*"] if Dir.exist?("policies")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tharvid/dvarapala/releases/download/v0.1.9/dvarapala_0.1.9_macos_arm64.tar.gz"
      sha256 "8b717fb3317adf4faf9a179c18e71a82cdbdd5c9ef8d4765e513e5ae0681bdbf"

      define_method(:install) do
        bin.install "dvarapala"
        pkgshare.install Dir["policies/*"] if Dir.exist?("policies")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tharvid/dvarapala/releases/download/v0.1.9/dvarapala_0.1.9_linux_x86_64.tar.gz"
      sha256 "a3da740d2c05d68b09140f3ec9918e4154eff60ada090f788e64ba5fbceb4c6d"
      define_method(:install) do
        bin.install "dvarapala"
        pkgshare.install Dir["policies/*"] if Dir.exist?("policies")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tharvid/dvarapala/releases/download/v0.1.9/dvarapala_0.1.9_linux_arm64.tar.gz"
      sha256 "173ebbc991caa30a78c2f098c22a9f9935906d73e88f29cb873158cbf57f0546"
      define_method(:install) do
        bin.install "dvarapala"
        pkgshare.install Dir["policies/*"] if Dir.exist?("policies")
      end
    end
  end

  test do
    system "#{bin}/dvarapala", "version"
  end
end
